dotExe/Aion/urls.py
from django.conf.urls import url
from .import views
app_name = 'Aion'

urlpatterns = [
    url(r'adminAddUser$' ,views.adminAddUser ,name='adminAddUser'),
    url(r'logOut$' ,views.logOut ,name='logOut'),
    url(r'accountingManagerFinancialDetails$' ,views.accountingManagerFinancialDetails ,name='accountingManagerFinancialDetails'),
    url(r'productManagerWatchUpdate/(?P<watchNo>[0-9]+)$' ,views.productManagerWatchUpdate ,name='productManagerWatchUpdate'),
    url(r'productManagerAddWatch$' ,views.productManagerAddWatch ,name='productManagerAddWatch'),
    url(r'productManagerDeleteWatch/(?P<watchNo>[0-9]+)$' ,views.productManagerDeleteWatch ,name='productManagerDeleteWatch'),
    url(r'homePage$',views.homePage ,name='homePage'),
    url(r'watchDetail/(?P<watchNo>[0-9]+)$' ,views.watchDetail ,name='watchDetail'),
    url(r'watchListFilter$' ,views.watchListFilter ,name='watchListFilter'),
    url(r'signUp$' ,views.signUp ,name='signUp'),
    url(r'signIn$' ,views.signIn ,name='signIn'),
    url(r'buyWatch/(?P<watchNo>[0-9]+)$' ,views.buyWatch ,name='buyWatch'),
    url(r'myProfile$' ,views.myProfile ,name='myProfile'),
    url(r'profileUpdate$' ,views.profileUpdate ,name='profileUpdate'),
    url(r'loginPage$' ,views.loginPage ,name='loginPage'),
    url(r'signUpPage$' ,views.signUpPage ,name='signUpPage'),
    url(r'editProfilePage$' ,views.editProfilePage ,name='editProfilePage'),
    url(r'addWatchPage$' ,views.addWatchPage ,name='addWatchPage'),
    url(r'editWatchPage$' ,views.editWatchPage ,name='editWatchPage'),
    url(r'edittingWatchPage/(?P<watchNo>[0-9]+)$' ,views.edittingWatchPage ,name='edittingWatchPage'),
    url(r'addUserPage$' ,views.addUserPage ,name='addUserPage'),
    url(r'listManagersPage$' ,views.listManagersPage ,name='listManagersPage'),
    url(r'transactionProcessed/(?P<watchNo>[0-9]+)$' ,views.transactionProcessed ,name='transactionProcessed'),
    url(r'giveReviewPage/(?P<watchNo>[0-9]+)$' ,views.giveReviewPage ,name='giveReviewPage'),
    url(r'finishReviewPage/(?P<watchNo>[0-9]+)$' ,views.finishReviewPage ,name='finishReviewPage'),
    url(r'addUserPage$' ,views.addUserPage ,name='addUserPage'),
    url(r'transactionPage$' ,views.transactionPage ,name='transactionPage'),
    url(r'managerTransactionPageOne$' ,views.managerTransactionPageOne ,name='managerTransactionPageOne'),
    url(r'managerTransactionPageTwo$' ,views.managerTransactionPageTwo ,name='managerTransactionPageTwo'),
    url(r'managerTransactionPageThree$' ,views.managerTransactionPageThree ,name='managerTransactionPageThree'),
    url(r'home$',views.homeBase ,name='homeBase'),
    url(r'^$',views.loginPage ,name='loginPage'),
]

dotExe/dotExe/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from Aion import views as Aion_views
from django.conf.urls import handler404, handler500


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Aion/', include('Aion.urls')),
#    url(r'session_security/', include('session_security.urls')),
]

handler404 = Aion_views.error_404
handler500 = Aion_views.error_500

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dotExe/Aion/forms.py
from django import forms
from .models import Product
from .models import User
from django.core.validators import validate_email

class ProductImageForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'product_quantity', 'product_price', 'product_rating', 'product_type']
#    	fields = ['product_name', 'product_quantity', 'product_price', 'product_rating', 'product_thumbnail', 'product_type']

class AdminUserImageForm(forms.ModelForm):

    user_password = forms.CharField(widget=forms.PasswordInput)	
    class Meta:
        model = User
#    	fields = ['user_username', 'user_password', 'user_privilege', 'user_first_name', 'user_last_name', 'user_middle_initial', 'user_email', 'user_thumbnail']
        fields = ['user_username', 'user_password', 'user_privilege', 'user_first_name', 'user_last_name', 'user_middle_initial', 'user_email']
    
class EditProfileForm(forms.ModelForm):
	
    user_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
#    	fields = ['user_username', 'user_password', 'user_first_name', 'user_last_name', 'user_middle_initial', 'user_email', 'user_thumbnail']
        fields = ['user_username', 'user_password', 'user_first_name', 'user_last_name', 'user_middle_initial', 'user_email']

dotExe/Aion/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import User, User_Info, Product, Product_Review, Transaction, Transaction_Extension, Common_Passwords, Common_Usernames
from django.core.files.storage import FileSystemStorage
from Aion.forms import ProductImageForm, AdminUserImageForm, EditProfileForm
from passlib.hash import pbkdf2_sha256
from datetime import datetime, timedelta
import dateutil.parser
import re
import logging
# Create your views here.



logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s:%(levelname)s:%(name)s:%(message)s')
file_handler = logging.FileHandler('dotExe.log')
file_handler.setFormatter(formatter)
logger.addHandler(file_handler)

def password_check(password):
    """
    Verify the strength of 'password'
    Returns a dict indicating the wrong criteria
    A password is considered strong if:
        8 characters length or more
        1 digit or more
        1 symbol or more
        1 uppercase letter or more
        1 lowercase letter or more
    """

    # calculating the length
    length_error = len(password) < 8

    # searching for digits
    digit_error = re.search(r"\d", password) is None

    # searching for uppercase
    uppercase_error = re.search(r"[A-Z]", password) is None

    # searching for lowercase
    lowercase_error = re.search(r"[a-z]", password) is None

    # searching for symbols
    symbol_error = re.search(r"\W", password) is None

    # overall result
    password_ok = not ( length_error or digit_error or uppercase_error or lowercase_error or symbol_error )

    return password_ok

def logOut(request):
    watch_list = Product.objects.order_by('-id')
    context = {
		'watchList': watch_list,
	}

    if 'timeout' in request.session:
        context['timeout'] = True
        del request.session['timeout']
    request.session.flush()
    request.session['user'] = -1

    return render(request, 'Aion/homepage.html',context)

def error_404(request):
        data = {}
        return render(request,'Aion/404.html', data)

def error_500(request):
        data = {}
        return render(request,'Aion/500.html', data)

def managerTransactionPageOne(request):
    user = get_object_or_404(User, pk = request.session['user'])
    transaction_list = Transaction.objects.all()
    filter1 = 1
    total = 0.0
    for x in transaction_list:
        total = total + x.transaction_order_total
    content = {
        'user':user,
        'transaction':transaction_list,
        'filter': filter1,
        'total':total
    }
    return render(request, 'Aion/viewtransact.html', content)

def managerTransactionPageTwo(request):
    user = get_object_or_404(User, pk = request.session['user'])
    transaction_list = Transaction.objects.all()
    filter2 = 2
    analog_watch = []
    digital_watch = []
    smart_watch = []
    analog_list = Product.objects.filter(product_type='0')
    digital_list = Product.objects.filter(product_type='1')
    smart_list = Product.objects.filter(product_type='2')
    analog_total = 0
    digital_total = 0
    smart_total = 0
    for y in transaction_list:
        if y.product_id.product_type == '0':
            analog_total = analog_total + y.transaction_order_total
            analog_watch.append(y)
        elif y.product_id.product_type == '1':
            digital_total = digital_total + y.transaction_order_total
            digital_watch.append(y)
        else:
            smart_total = smart_total + y.transaction_order_total
            smart_watch.append(y)
    content = {
        'user':user,
        'analog':analog_watch,
        'digital':digital_watch,
        'smart':smart_watch,
        'filter':filter2,
        'total1': analog_total,
        'total2': digital_total,
        'total3': smart_total
    }
    return render(request, 'Aion/viewtransact.html', content)

def managerTransactionPageThree(request):
    user = get_object_or_404(User, pk = request.session['user'])
    transaction_list = Transaction.objects.all()
    product_list = Product.objects.all()
    product_list_bought = Product.objects.filter(product_bought = 1)
    product_no_transaction = Product.objects.filter(product_bought = 0)
    allName = {}
    totalPerProduct = {}
    a = 0
    for x in product_list:
        allName[a] = x
        totalPerProduct[a] = 0.0
        a = a + 1
    transaction_total = Transaction_Extension.objects.all()
    filter3 = 3
    content = {
        'user':user,
        'transaction':transaction_list,
        'filter': filter3,
        'totalPerProduct': transaction_total,
        'product': product_list_bought,
        'noTransactions': product_no_transaction
    }
    return render(request, 'Aion/viewtransact.html', content)

def transactionPage(request):
    user = get_object_or_404(User, pk = request.session['user'])
    user_transaction = Transaction.objects.filter(transaction_user = user)
    context ={
        'user': user,
        'transactions':user_transaction
    }
    return render(request, 'Aion/usertransactions.html', context)

def giveReviewPage(request, watchNo):
    user = get_object_or_404(User, pk = request.session['user'])
    chosen_watch = get_object_or_404(Product, pk=watchNo)
    context={
        'item': chosen_watch,
        'user': user
    }
    return render(request, 'Aion/reviewpage.html', context)

def finishReviewPage(request, watchNo):
    user = get_object_or_404(User, pk = request.session['user'])
    chosen_watch = get_object_or_404(Product, pk=watchNo)
    new_review = Product_Review(product_id=chosen_watch, product_user_review=user, product_comment=request.POST['UserReview'])
    new_review.save()
    good = 0
    watch_review = None
    transaction_list = Transaction.objects.all()
    try:
        watch_review = Product_Review.objects.filter(product_id=chosen_watch)
    except Product_Review.DoesNotExist:
        watch_review = None
    for x in transaction_list:
        if x.transaction_user == user:
            if x.product_id == chosen_watch:
                good = 1
    if watch_review:
        context = {
            'item':chosen_watch,
            'user':user,
            'good':good,
            'review': watch_review
        }
    else:
        context = {
        'item':chosen_watch,
        'good':good,
        'user':user
    }
    return render(request, 'Aion/watchdetails.html', context)

def transactionProcessed(request, watchNo):
    user = get_object_or_404(User, pk = request.session['user'])
    bought_watch = get_object_or_404(Product, pk=watchNo)
    bought_watch.product_quantity = bought_watch.product_quantity - int(request.POST['TransactionQuantity'])
    bought_watch.product_bought = 1
    bought_watch.save()
    costing = float(request.POST['TransactionQuantity']) * bought_watch.product_price
    make_transaction = Transaction(transaction_user=user, product_id=bought_watch, transaction_quantity=request.POST['TransactionQuantity'], transaction_order_total=costing)
    make_transaction.save()
    try:
        transactionExtension = Transaction_Extension.objects.get(product_id = bought_watch)
        transactionExtension.transaction_total = transactionExtension.transaction_total + costing
        transactionExtension.save()
    except Transaction_Extension.DoesNotExist:
        transactionExtension = Transaction_Extension(product_id=bought_watch, transaction_total=costing)
        transactionExtension.save()
    
    if user.user_privilege == '3':
        user_info = get_object_or_404(User_Info, user_id = user)
        context = {
            'user': user,
            'userInfo': user_info,
        }
    else:
        context = {
        'user': user,
	}
    return render(request, 'Aion/viewprofile.html', context)
    

def listManagersPage(request):
    user_list_product = User.objects.filter(user_privilege = '1')
    user_list_accounting = User.objects.filter(user_privilege = '2') 
    user = get_object_or_404(User, pk=request.session['user'])
    content = {
        'user':user,
        'productManagers': user_list_product,
        'accountingManagers': user_list_accounting,
    }
    return render(request, 'Aion/listofmanagers.html', content)

def loginPage(request):
    request.session['user'] = -1
    return render(request, 'Aion/login.html')

def signUpPage(request):
    request.session['user'] = -1
    form = EditProfileForm(request.POST , request.FILES)
    content = {
        'form':form
    }
    return render(request, 'Aion/signup.html', content)

def editWatchPage(request):
    user = get_object_or_404(User, pk=request.session['user'])
    watch_list = Product.objects.order_by('-id')
    content = {
        'user':user,
        'watchList':watch_list,
        
    }
    return render(request, 'Aion/listwatches.html', content)

def edittingWatchPage(request, watchNo):
    user = get_object_or_404(User, pk=request.session['user'])
    form = ProductImageForm(request.POST , request.FILES )
    watch = get_object_or_404(Product, pk=watchNo)
    content = {
        'user':user,
        'watch':watch,
        'form':form
    }
    return render(request, 'Aion/editwatch.html', content)

def addWatchPage(request):
    user = get_object_or_404(User, pk=request.session['user'])
    form = ProductImageForm(request.POST, request.FILES)
    content = {
        'user':user,
        'form':form
    }
    return render(request, 'Aion/addwatch.html', content)

def editProfilePage(request):
    form = EditProfileForm(request.POST, request.FILES)
    user = get_object_or_404(User, pk=request.session['user'])
    content = {
        'user': user,
        'form': form
    }
    return render(request, 'Aion/editprofile.html', content)

def addUserPage(request):
    user = get_object_or_404(User, pk=request.session['user'])
    admin_choices ={
        ('1', 'Product Manager'),
        ('2', 'Accounting Manager')
    }

dotExe/Aion/templates/Aion/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Aion Watch</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Aion/adduser.css' %}">
</head>
<body>

    <div class="navbar">
        <div class="navbar-contents">
            {% if request.session.user > 0 %}
            <a href="{% url 'Aion:homePage' %}" id="home">Aion Watch</a>
            {% else %}
            <a href="{% url 'Aion:homeBase' %}" id="home">Aion Watch</a>
            {% endif %}
        </div>
        <div class="navbar-contents">
            {% if user.user_privilege == '0' %}
            <a href="{% url 'Aion:addUserPage' %}">Add User</a>
            <a href="{% url 'Aion:listManagersPage'%}">List of Managers</a>
            {% elif user.user_privilege == '1' %}
            <a href="{% url 'Aion:addWatchPage' %}">Add Watches</a>
            <a href="{% url 'Aion:editWatchPage' %}">List Watches</a>
            {% elif user.user_privilege == '2' %}
            <a href="{% url 'Aion:managerTransactionPageOne' %}">View Transactions</a>
            {% endif %}
            <a href="{% url 'Aion:myProfile' %}">Profile</a>
            <a href="{% url 'Aion:loginPage' %}">Logout</a>
        </div>
    </div>
    
    <div class="main">
        <div class="loginbox">
            <h1>Add User</h1>
            <form action="{% url 'Aion:adminAddUser' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="inputbox">    
            {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {% endfor %}
                <button>Submit</button>
            </div>
            </form>
        </div>
    </div>
</body>
</html>

dotExe/Aion/templates/Aion/addwatch.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Aion Watch</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Aion/addwatch.css' %}">
</head>
<body>

    <div class="navbar">
        <div class="navbar-contents">
            {% if request.session.user > 0 %}
            <a href="{% url 'Aion:homePage' %}" id="home">Aion Watch</a>
            {% else %}
            <a href="{% url 'Aion:homeBase' %}" id="home">Aion Watch</a>
            {% endif %}
        </div>
        <div class="navbar-contents">
            {% if user.user_privilege == '0' %}
            <a href="{% url 'Aion:addUserPage' %}">Add User</a>
            <a href="{% url 'Aion:listManagersPage'%}">List of Managers</a>
            {% elif user.user_privilege == '1' %}
            <a href="{% url 'Aion:addWatchPage' %}">Add Watches</a>
            <a href="{% url 'Aion:editWatchPage' %}">List Watches</a>
            {% elif user.user_privilege == '2' %}
            <a href="{% url 'Aion:managerTransactionPageOne' %}">View Transactions</a>
            {% endif %}
            <a href="{% url 'Aion:myProfile' %}">Profile</a>
            <a href="{% url 'Aion:loginPage' %}">Logout</a>
        </div>
    </div>
    
    <div class="main">
        <div class="loginbox">
            <h1>Add Watch</h1>
            <form action="{% url 'Aion:productManagerAddWatch' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="inputbox">    
            {% for field in form %}
                {{ field.label_tag }}
                {{ field }}
<!--
                <input type="text" value="" placeholder="Product Name" id="productname" name="ProductAddName"/>
                <select class="user" name="ProductAddType">
                    <option value="0">Analog Watch </option>
                    <option value="1">Digital Watch </option>
                    <option value="2">Smart Watch </option>
                </select>
                <input type="text" value="" placeholder="Quantity" id="quantity" name="ProductAddQuantity"/>
                <input type="text" value="" placeholder="Price" id="price" name="ProductAddPrice"/>
                <select class="user" name="ProductAddRating">
                    <option value="1">1 Star </option>
                    <option value="2">2 Stars </option>
                    <option value="3" selected>3 Stars </option>
                    <option value="4">4 Stars </option>
                    <option value="5">5 Stars </option>
                </select>
                <input type="file" name="ProductAddPicture">
-->
            {% endfor %}
                <button>Submit</button>
            </div>
            </form>
        </div>
    </div>
    

</body>
</html>

dotExe/Aion/templates/Aion/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Aion Watch</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Aion/homepage.css' %}">
</head>
<body>
    {% if timeout %}
        <script type="text/javascript">alert("You have been Logged out due to inactivity.")</script>
    {% endif %}
    <div class="navbar">
        <div class="navbar-contents">
            {% if request.session.user > 0 %}
            <a href="{% url 'Aion:homePage' %}" id="home">Aion Watch</a>
            {% else %}
            <a href="{% url 'Aion:homeBase' %}" id="home">Aion Watch</a>
            {% endif %}
        </div>
        <div class="navbar-contents">
            {% if request.session.user > 0 %}
                {% if user.user_privilege == '0' %}
                <a href="{% url 'Aion:addUserPage' %}">Add User</a>
                <a href="{% url 'Aion:listManagersPage'%}">List of Managers</a>
                {% elif user.user_privilege == '1' %}
                <a href="{% url 'Aion:addWatchPage' %}">Add Watches</a>
                <a href="{% url 'Aion:editWatchPage' %}">List Watches</a>
                {% elif user.user_privilege == '2' %}
                <a href="{% url 'Aion:managerTransactionPageOne' %}">View Transactions</a>
                {% endif %}
            <a href="{% url 'Aion:myProfile' %}">Profile</a>
            <a href="{% url 'Aion:homeBase' %}">Logout</a>
            {% else %}
            <a href="{% url 'Aion:loginPage' %}">Log In</a>
            <a href="{% url 'Aion:signUpPage' %}">Sign Up</a>
            {% endif %}
        </div>
    </div>
    
    <div class="main-gallery">
        {% for item in watchList %}
        <div class="item"> 
            <a href="{% url 'Aion:watchDetail' item.pk %}">
                <img src="{{ item.product_thumbnail.url }}" width="200" height="250">
            </a>
            <div class="details">
                <a href="{% url 'Aion:watchDetail' item.pk %}">{{ item.product_name }}</a>
                <p>Price: Php{{ item.product_price }}</p>
                {% if item.product_type == '0' %}
                <p>Type: Analog Watch</p>
                {% elif item.product_type == '1' %}
                <p>Type: Digital Watch</p>
                {% elif item.product_type == '2' %}
                <p>Type: Smart Watch</p>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>

dotExe/Aion/templates/Aion/reviewpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Aion Watch</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Aion/reviewpage.css' %}">
</head>
<body>

    <div class="navbar">
        <div class="navbar-contents">
            {% if request.session.user > 0 %}
            <a href="{% url 'Aion:homePage' %}" id="home">Aion Watch</a>
            {% else %}
            <a href="{% url 'Aion:homeBase' %}" id="home">Aion Watch</a>
            {% endif %}
        </div>
        <div class="navbar-contents">
            {% if user.user_privilege == '0' %}
            <a href="{% url 'Aion:addUserPage' %}">Add User</a>
            <a href="{% url 'Aion:listManagersPage'%}">List of Managers</a>
            {% elif user.user_privilege == '1' %}
            <a href="{% url 'Aion:addWatchPage' %}">Add Watches</a>
            <a href="{% url 'Aion:editWatchPage' %}">List Watches</a>
            {% elif user.user_privilege == '2' %}
            <a href="{% url 'Aion:managerTransactionPageOne' %}">View Transactions</a>
            {% endif %}
            <a href="{% url 'Aion:myProfile' %}">Profile</a>
            <a href="{% url 'Aion:loginPage' %}">Logout</a>
        </div>
    </div>
    
    <div class="main">
        <div class="review">
            <div class="form-container">
                <h1>Review The Item</h1>
                <form action="{% url 'Aion:finishReviewPage' item.pk %}" method="post">
                    {% csrf_token %}
                    <div class="revbox">
                        <textarea placeholder="Input review here..." name="UserReview" cols="50" rows="5"></textarea>
                        <button class="button">Submit</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</body>
</html>

dotExe/Aion/templates/Aion/viewtransact.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Time Watch</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Aion/viewtransact.css' %}">
</head>
<body>

    <div class="navbar">
        <div class="navbar-contents">
             {% if request.session.user > 0 %}
            <a href="{% url 'Aion:homePage' %}" id="home">Aion Watch</a>
            {% else %}
            <a href="{% url 'Aion:homeBase' %}" id="home">Aion Watch</a>
            {% endif %}
        </div>
        <div class="navbar-contents">
            {% if user.user_privilege == '0' %}
            <a href="{% url 'Aion:addUserPage' %}">Add User</a>
            <a href="{% url 'Aion:listManagersPage'%}">List of Managers</a>
            {% elif user.user_privilege == '1' %}
            <a href="{% url 'Aion:addWatchPage' %}">Add Watches</a>
            <a href="{% url 'Aion:editWatchPage' %}">List Watches</a>
            {% elif user.user_privilege == '2' %}
            <a href="{% url 'Aion:managerTransactionPageOne' %}">View Transactions</a>
            {% endif %}
            <a href="{% url 'Aion:myProfile' %}">Profile</a>
            <a href="{% url 'Aion:loginPage' %}">Logout</a>
        </div>
    </div>
    
    <div class="toptbox">
        <h1>Transactions</h1>
        <div class="buttons">
            <a href="{% url 'Aion:managerTransactionPageOne' %}">Total Sales</a>
            <a href="{% url 'Aion:managerTransactionPageTwo' %}">Sales By Type</a>
            <a href="{% url 'Aion:managerTransactionPageThree' %}">Sales By Product</a>
        </div>
    </div>
    {% if filter == 1 %}
    <div class="transactionbox">    
        <div class="tablebox">
            <table width="100%">
                <tr>
                    <th>Product Name</th>
                    <th>Date</th>
                    <th>Sales</th>
                </tr>
                {% for trans in transaction %}
                <tr>
                    <td>{{ trans.product_id.product_name }}</td>
                    <td>{{ trans.transaction_date }}</td>
                    <td>Php{{trans.product_id.product_price}} X {{trans.transaction_quantity}} = Php{{ trans.transaction_order_total }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="totalbox">
            <h2>Total Sales: Php{{total}}</h2>
        </div>
    </div>
    {% elif filter == 2 %}
    <div class="transactionbox">    
        <div class="tablebox">
            <table width="100%">
                <tr>
                    <th>Product Name [ ANALOG WATCH ]</th>
                    <th>Date</th>
                    <th>Sales</th>
                </tr>
                {% for trans in analog %}
                <tr>
                    <td>{{ trans.product_id.product_name }}</td>
                    <td>{{ trans.transaction_date }}</td>
                    <td>Php{{trans.product_id.product_price}} X {{trans.transaction_quantity}} = Php{{ trans.transaction_order_total }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="totalbox">
            <h2>Total Sales: Php{{total1}}</h2>
        </div>
    </div>
    <div class="transactionbox">    
        <div class="tablebox">
            <table width="100%">
                <tr>
                    <th>Product Name [ DIGITAL WATCH ]</th>
                    <th>Date</th>
                    <th>Sales</th>
                </tr>
                {% for trans in digital %}
                <tr>
                    <td>{{ trans.product_id.product_name }}</td>
                    <td>{{ trans.transaction_date }}</td>
                    <td>Php{{trans.product_id.product_price}} X {{trans.transaction_quantity}} = Php{{ trans.transaction_order_total }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="totalbox">
            <h2>Total Sales: Php{{total2}}</h2>
        </div>
    </div>
    <div class="transactionbox">    
        <div class="tablebox">
            <table width="100%">
                <tr>
                    <th>Product Name [ SMART WATCH ]</th>
                    <th>Date</th>
                    <th>Sales</th>
                </tr>
                {% for trans in smart %}
                <tr>
                    <td>{{ trans.product_id.product_name }}</td>
                    <td>{{ trans.transaction_date }}</td>
                    <td>Php{{trans.product_id.product_price}} X {{trans.transaction_quantity}} = Php{{ trans.transaction_order_total }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="totalbox">
            <h2>Total Sales: Php{{total3}}</h2>
        </div>
    </div>
    {% elif filter == 3 %}
        {% for item in product %}
        <div class="transactionbox">    
            <div class="tablebox">
                <table width="100%">
                    <tr>
                        <th>Product Name [ {{item.product_name}} ]</th>
                        <th>Date</th>
                        <th>Sales</th>
                    </tr>
                    {% for trans2 in transaction %}
                        {% if trans2.product_id.product_name == item.product_name %}
                            <tr>
                                <td>{{ trans2.product_id.product_name }}</td>
                                <td>{{ trans2.transaction_date }}</td>
                                <td>Php{{trans2.product_id.product_price}} X {{trans2.transaction_quantity}} = Php{{ trans2.transaction_order_total }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
            </div>
            {% for totality in totalPerProduct %}
                {% if totality.product_id == item %}
                <div class="totalbox">
                    <h2>Total Sales: Php{{totality.transaction_total}} </h2>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endfor %}
        {% for item in noTransactions%}
        <div class="transactionbox">    
                <div class="tablebox">
                    <table width="100%">
                        <tr>
                            <th>Product Name [ {{item.product_name}} ]</th>
                            <th>Date</th>
                            <th>Sales</th>
                        </tr>
                        <tr>
                            <td>No Transactions Available</td>
                            <td>No Transactions Available</td>
                            <td>No Transactions Available</td>
                        </tr>
                    </table>
                </div>
                <div class="totalbox">
                    <h2>Total Sales: No Transactions Available</h2>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</body>
</html>